 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/calculations", type: :request do
  # Calculation. As you add validations to Calculation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Calculation.create! valid_attributes
      get calculations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      calculation = Calculation.create! valid_attributes
      get calculation_url(calculation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_calculation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      calculation = Calculation.create! valid_attributes
      get edit_calculation_url(calculation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Calculation" do
        expect {
          post calculations_url, params: { calculation: valid_attributes }
        }.to change(Calculation, :count).by(1)
      end

      it "redirects to the created calculation" do
        post calculations_url, params: { calculation: valid_attributes }
        expect(response).to redirect_to(calculation_url(Calculation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Calculation" do
        expect {
          post calculations_url, params: { calculation: invalid_attributes }
        }.to change(Calculation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post calculations_url, params: { calculation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested calculation" do
        calculation = Calculation.create! valid_attributes
        patch calculation_url(calculation), params: { calculation: new_attributes }
        calculation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the calculation" do
        calculation = Calculation.create! valid_attributes
        patch calculation_url(calculation), params: { calculation: new_attributes }
        calculation.reload
        expect(response).to redirect_to(calculation_url(calculation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        calculation = Calculation.create! valid_attributes
        patch calculation_url(calculation), params: { calculation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested calculation" do
      calculation = Calculation.create! valid_attributes
      expect {
        delete calculation_url(calculation)
      }.to change(Calculation, :count).by(-1)
    end

    it "redirects to the calculations list" do
      calculation = Calculation.create! valid_attributes
      delete calculation_url(calculation)
      expect(response).to redirect_to(calculations_url)
    end
  end
end
